requires 'Dancer2';
requires 'MongoDB';
requires 'JSON';
requires 'JSON::MaybeXS';
requires 'Crypt::PBKDF2';
requires 'Plack';
requires 'Test::More';
requires 'Test::MockModule';
requires 'HTTP::Request::Common';